name: "order-web"
host: "host.docker.internal"
port: 8083
tags: [ "order-web","yunfeiyang" ]
order_srv:
  name: "order-srv"
  host: "127.0.0.1"
  port: 50054
goods_srv:
  name: "goods-srv"
  host: "127.0.0.1"
  port: 50052
inventory_srv:
  name: "inventory-srv"
  host: "127.0.0.1"
  port: 50053
jwt:
  key: "ssdeaqeeqq"
alipay:
  app_id: "2016101100666266"
  private_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  ali_public_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  notify_url: "http://localhost:8083/alipay/notify"
  return_url: "http://localhost:8083/alipay/return"
redis:
  host: "127.0.0.1"
  port: 6379
  expire: 300 # 单位秒
consul:
  host: "localhost"
  port: 8500
nacos:
  host: "localhost"
  port: 8848
  group: "dev"
  namespace: "4ee52c31-141b-4a20-bd64-e3b6618fa0d3"
  dataid: "order-web-config.json"
  user: "nacos"
  password: "nacos"
otel_collector:
  url: "http://127.0.0.1:14268/api/traces"