version: "3.8"

services:
  #  consul:
  #    image: consul:1.11
  #    container_name: consul
  #    ports:
  #      - "8500:8500"
  #      - "8300:8300"
  #      - "8301:8301"
  #      - "8302:8302"
  #      - "8600:8600/udp"
  #    command: consul agent -server -bootstrap-expect 1 -node consul_server_master -data-dir /tmp/data-dir -client 0.0.0.0 -ui
  #    healthcheck:
  #      test: [ "CMD", "curl", "-f", "http://consul:8500" ]
  #      interval: 30s
  #      timeout: 5s
  #      retries: 5
  #  nacos:
  #    image: nacos/nacos-server
  #    container_name: nacos-standalone
  #    environment:
  #      - MODE=standalone
  #      - JVM_XMS=512m
  #      - JVM_XMX=512m
  #      - JVM_XMN=256m
  #    ports:
  #      - "8848:8848"
  #      - "9848:9848"

  elasticsearch:
    image: elasticsearch:7.10.1  #镜像
    container_name: elk_elasticsearch  #定义容器名称
    restart: always  #开机启动，失败也会一直重启
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./data/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
    #      - /data/elk/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.10.1
    container_name: elk_kibana
    restart: always
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
    ports:
      - "5601:5601"
#  logstash:
#    image: logstash:7.10.1
#    container_name: elk_logstash
#    restart: always
#    volumes:
#      - /data/elk/logstash/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
#    depends_on:
#      - elasticsearch #kibana在elasticsearch启动之后再启动
#    links:
#      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
#    ports:
#      - 4560:4560