name: "goods-web"
host: "host.docker.internal"
port: 8082
tags: [ "goods-web","yunfeiyang" ]
goods_srv:
  name: "goods-srv"
  host: "127.0.0.1"
  port: 50052
jwt:
  key: "ssdeaqeeqq"
redis:
  host: "127.0.0.1"
  port: 6379
  expire: 300 # 单位秒
consul:
  host: "localhost"
  port: 8500
nacos:
  host: "localhost"
  port: 8848
  group: "dev"
  namespace: "4ee52c31-141b-4a20-bd64-e3b6618fa0d3"
  dataid: "goods-web-config.json"
  user: "nacos"
  password: "nacos"