name: "goods-srv"
host: "0.0.0.0"
port: 50052
tags: [ "goods-srv","yunfeiyang" ]
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  db: "shop_goods_srv"
consul:
  host: "localhost"
  port: 8500
es:
  host: "localhost"
  port: 9200