version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./bbs:/usr/share/nginx/bbs"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"